# Install script for directory: /home/negi/Development/Android/paymon/app/libs/boringssl/crypto

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/negi/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/user")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/stack/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/lhash/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/err/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/buf/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/base64/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/bytestring/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/pool/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/rc4/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/conf/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/chacha/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/poly1305/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/curve25519/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/digest_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/cipher_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/rand_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/bio/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/bn_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/obj/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/asn1/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/engine/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/dh/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/dsa/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/rsa_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/ec_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/ecdh/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/ecdsa_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/hmac_extra/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/cmac/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/evp/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/hkdf/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/pem/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/x509/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/x509v3/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/pkcs7/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/pkcs8/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/test/cmake_install.cmake")
  include("/home/negi/Development/Android/paymon/app/libs/boringssl/build-android/crypto/fipsmodule/cmake_install.cmake")

endif()

